version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # adjust based on your frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
